@startuml

!include https://raw.githubusercontent.com/Kyrales/1C-ER-plantuml/refs/heads/extended/main.puml

title ER - Диаграмма системы планирования загрузок
caption Диаграмма объектов

package НСИ <<folder>> {

    _Справочник(Контрагенты, "Контрагенты"){
        Заказчик (Булево)
        Перевозчик (Булево)
        ИНН  (Строка)
        КПП (Строка)
        Контакты (Строка)  
    }

    _Справочник(Валюты, "Валюты")
    _Справочник(Услуги, "Услуги")
    _Справочник(Пользователи, "Пользователи")
    _Справочник(Грузы, "Грузы"){
        Категория
        Вес (Число)
        Объем (Число)
        ТребованияКТС (Строка)
    }
    _Справочник(Организации, "Организации"){
        ИНН  (Строка)
        КПП (Строка)   
        БанковскиеРеквизиты (Строка)
    }
    _Справочник(НаправленияПеревозок, "Направления перевозок"){
        ПунктОтправления (Строка)
        ПунктНазначения (Строка)   
        Расстояние (Число)    
    }

}

package ОперативныйУчет <<folder>> {
    
    _Перечисление(СтатусыЗаявок, "Статусы заявок"){
        Черновик
        ВРаботе
        Закрыт
        Отменен
    }

    _Перечисление(КатегорииГрузов, "Категории грузов"){
        Обычный
        Хрупкий
        Опасный
        Скоропортящийся
        Крупногабаритный
    }

    _Документ(ЗаявкаОтЗаказчика, "Заявка от заказчика") {
        Контрагент 
        Организация
        Валюта
        СуммаДокумента (Число)
        Перевозка 
        Направление
        Ответственный 
        Статус
        Комментарий (Строка)
        -- Услуги --
        Услуга
        Сумма (Число)
        СуммаУпр (Число)
         -- Грузы --
        Груз
    }

    _Документ(ЗапросНаПеревозку, "Запрос на перевозку") {
        Контрагент 
        Организация
        Валюта
        СуммаДокумента (Число)
        Перевозка 
        Направление
        ПлановаяДатаЗагрузки (Дата)
        ПлановаяДатаРазгрузки (Дата)
        Ответственный 
        Комментарий (Строка)
        -- Услуги --
        Услуга
        Сумма (Число)
        СуммаУпр (Число)
         -- Грузы --
        Груз
        Заявка
    }  

    _Документ(Перевозка, "Перевозка") {
        -- Перевозки --
        Заявка
        Запрос
        Груз
    } 

    _РегистрНакопления(ОтложенныеВзаиморасчеты, "Отложенные взаиморасчеты") {
        <$d> Организация
        <$d> Контрагент
        <$d> Перевозка
        <$d> ДокументВзаиморасчетов
        <$d> Валюта
        <$r> Сумма
        <$r> СуммаУпр    
    }

}

package ФинансовыйУчет <<folder>> {

    _Документ(РеализацияУслуг, "Реализация услуг") {
        Контрагент 
        Организация
        Валюта
        СуммаДокумента (Число)
        Ответственный 
        Комментарий (Строка)
        -- Услуги --
        Услуга
        Заявка
        Перевозка
        Сумма (Число)
        СуммаУпр (Число)       
    }

    _Документ(ПоступлениеУслуг, "Поступление услуг") {
        Контрагент 
        Организация
        Валюта
        СуммаДокумента (Число)
        Ответственный 
        Комментарий (Строка)
        -- Услуги --
        Услуга
        Запрос
        Перевозка
        ДатаЗагрузки (Дата)
        ДатаРазгрузки (Дата)
        Сумма (Число)
        СуммаУпр (Число)       
    }

    _Документ(ПоступлениеДенежныхСредств, "Поступление денежных средств") {
        Организация
        Валюта
        СуммаДокумента (Число)
        Ответственный 
        Комментарий (Строка)
        -- РасшифровкаПлатежа --
        Основание
        Контрагент
        Перевозка
        Сумма (Число)
        СуммаУпр (Число)       
    }

    _Документ(СписаниеДенежныхСредств, "Списание денежных средств") {
        Организация
        Валюта
        СуммаДокумента (Число)
        Ответственный 
        Комментарий (Строка)
        -- РасшифровкаПлатежа --
        Основание
        Контрагент
        Перевозка
        Сумма (Число)
        СуммаУпр (Число)       
    }

    _РегистрНакопления(ВзаиморасчетыСКонтрагентами, "Взаиморасчеты с контрагентами") {
        <$d> Организация
        <$d> Контрагент
        <$d> Перевозка
        <$d> ДокументВзаиморасчетов
        <$d> Валюта
        <$r> Сумма
        <$r> СуммаУпр    
    }

     _РегистрНакопления(Оплаты, "Оплаты") {
        <$d> Организация
        <$d> Контрагент
        <$r> Сумма    
    }

}

Услуги --> ЗаявкаОтЗаказчика::Услуга
Услуги --> ЗапросНаПеревозку::Услуга
Услуги --> РеализацияУслуг::Услуга
Услуги --> ПоступлениеУслуг::Услуга

Контрагенты --> ЗаявкаОтЗаказчика::Контрагент
Контрагенты --> ЗапросНаПеревозку::Контрагент
Контрагенты --> РеализацияУслуг::Контрагент
Контрагенты --> ПоступлениеУслуг::Контрагент
Контрагенты --> ВзаиморасчетыСКонтрагентами::Контрагент
Контрагенты --> ОтложенныеВзаиморасчеты::Контрагент
Контрагенты --> ПоступлениеДенежныхСредств::Контрагент
Контрагенты --> СписаниеДенежныхСредств::Контрагент
Контрагенты --> Оплаты::Контрагент

Организации --> ЗаявкаОтЗаказчика::Организация
Организации --> ЗапросНаПеревозку::Организация
Организации --> РеализацияУслуг::Организация
Организации --> ПоступлениеУслуг::Организация
Организации --> ВзаиморасчетыСКонтрагентами::Организация
Организации --> ОтложенныеВзаиморасчеты::Организация
Организации --> ПоступлениеДенежныхСредств::Организация
Организации --> СписаниеДенежныхСредств::Организация
Организации --> Оплаты::Организация

Валюты --> ЗаявкаОтЗаказчика::Валюта
Валюты --> ЗапросНаПеревозку::Валюта
Валюты --> РеализацияУслуг::Валюта
Валюты --> ПоступлениеУслуг::Валюта
Валюты --> ВзаиморасчетыСКонтрагентами::Валюта
Валюты --> ОтложенныеВзаиморасчеты::Валюта
Валюты --> ПоступлениеДенежныхСредств::Валюта
Валюты --> СписаниеДенежныхСредств::Валюта

Грузы --> ЗаявкаОтЗаказчика::Груз
Грузы --> ЗапросНаПеревозку::Груз
Грузы --> Перевозка::Груз

Перевозка --> ЗаявкаОтЗаказчика::Перевозка
Перевозка --> ЗапросНаПеревозку::Перевозка
Перевозка --> РеализацияУслуг::Перевозка
Перевозка --> ПоступлениеУслуг::Перевозка
Перевозка --> ВзаиморасчетыСКонтрагентами::Перевозка
Перевозка --> ОтложенныеВзаиморасчеты::Перевозка
Перевозка --> ПоступлениеДенежныхСредств::Перевозка
Перевозка --> СписаниеДенежныхСредств::Перевозка

Пользователи --> ЗаявкаОтЗаказчика::Ответственный
Пользователи --> ЗапросНаПеревозку::Ответственный
Пользователи --> РеализацияУслуг::Ответственный
Пользователи --> ПоступлениеУслуг::Ответственный
Пользователи --> ПоступлениеДенежныхСредств::Ответственный
Пользователи --> СписаниеДенежныхСредств::Ответственный

СтатусыЗаявок --> ЗаявкаОтЗаказчика::Статус
КатегорииГрузов --> Грузы::Категория

ЗаявкаОтЗаказчика --> ОтложенныеВзаиморасчеты::ДокументВзаиморасчетов
ЗаявкаОтЗаказчика --> Перевозка::Заявка
ЗаявкаОтЗаказчика --> ЗапросНаПеревозку::Заявка

ЗапросНаПеревозку --> ОтложенныеВзаиморасчеты::ДокументВзаиморасчетов
ЗапросНаПеревозку --> Перевозка::Запрос

НаправленияПеревозок --> ЗаявкаОтЗаказчика::Направление
НаправленияПеревозок --> ЗапросНаПеревозку::Направление

РеализацияУслуг --> ВзаиморасчетыСКонтрагентами
РеализацияУслуг --> ВзаиморасчетыСКонтрагентами::ДокументВзаиморасчетов
РеализацияУслуг --> ОтложенныеВзаиморасчеты

ПоступлениеУслуг --> ВзаиморасчетыСКонтрагентами
ПоступлениеУслуг --> ВзаиморасчетыСКонтрагентами::ДокументВзаиморасчетов
ПоступлениеУслуг --> ОтложенныеВзаиморасчеты

ПоступлениеДенежныхСредств --> ВзаиморасчетыСКонтрагентами
ПоступлениеДенежныхСредств --> Оплаты

СписаниеДенежныхСредств --> ВзаиморасчетыСКонтрагентами
СписаниеДенежныхСредств --> Оплаты

@enduml